algoritmo "CNH"

var
   nome: literal
   idade: inteiro

inicio

      escreva ("Usuário, informe seu nome: ")
      leia (nome)
      escreva ("Agora informe sua idade: ")
      leia (idade)
      
      se (idade >= 18) entao
         escreval
         escreval (nome, ", você pode obter sua cnh.")
      senao
         escreval
         escreval (nome, ", você não pode obter sua cnh.")
      fimse

fimalgoritmo


