algoritmo "Operação Para e Enquanto"

var

   iPara, iEnquanto : inteiro

inicio

      para iPara <- 0 ate 10 faca
           escreval ("O valor de i é: ", iPara)
      fimpara
           
      escreval
      
      enquanto iEnquanto <= 10 faca
               escreval ("O valor de i é: ", iEnquanto)
               iEnquanto <- iEnquanto + 1
      fimenquanto


fimalgoritmo
